[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 1000000
upload_speed = 460800
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

; After one serial flash containing ArduinoOTA, future updates can use Wi-Fi.
; Override --upload-port with the ESP IP if mDNS is unavailable.
[env:esp01_1m_ota]
extends = env:esp01_1m
upload_protocol = espota
upload_port = audio-esp01.local
